Fix/classpath step 2 (#305)
* Example for polars use (#120)

* Example for polars use

* Reformatted it to solve merge conflicts

---------

Co-authored-by: Maximilian Hess <maximilian.hess@ascii.ac.at>

* Sync branches (#134)

* fix again

* Translation of HS-Codes (#269)

* Cahnged folder structure to be more clear

* deepl translation failed

* Improved the ranking in the scan dashboard

* add new models (#271)

Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>

* refine llm docs (#272)

Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>

* Finalised translations

* Feat/refined dns (#274)

* replace to nicer values

* update deps

---------

Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>

* add citation (#273)

Co-authored-by: Hernan Picatto <hernan.picatto@ascii.ac.at>

* upgrade chatllm (#275)

Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>

* upgrade google models (#276)

Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>

* update owui (#277)

Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>

* upgrade 069 and fix some bugs (#278)

Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>

* Reorganised my scan folder

* Made str more general and used ibis instead of polars

* New pixi.toml in my subfolder

---------

Co-authored-by: geoHeil <1694964+geoHeil@users.noreply.github.com>
Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>
Co-authored-by: HPicatto <h.picatto@gmail.com>
Co-authored-by: Hernan Picatto <hernan.picatto@ascii.ac.at>

* Example for polars use (#120)

* Example for polars use

* Reformatted it to solve merge conflicts

---------

Co-authored-by: Maximilian Hess <maximilian.hess@ascii.ac.at>

* Sync branches (#134)

* fix again

* Translation of HS-Codes (#269)

* Cahnged folder structure to be more clear

* deepl translation failed

* Improved the ranking in the scan dashboard

* add new models (#271)

Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>

* refine llm docs (#272)

Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>

* Finalised translations

* Feat/refined dns (#274)

* replace to nicer values

* update deps

---------

Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>

* add citation (#273)

Co-authored-by: Hernan Picatto <hernan.picatto@ascii.ac.at>

* upgrade chatllm (#275)

Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>

* upgrade google models (#276)

Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>

* update owui (#277)

Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>

* upgrade 069 and fix some bugs (#278)

Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>

* Reorganised my scan folder

* Made str more general and used ibis instead of polars

* New pixi.toml in my subfolder

---------

Co-authored-by: geoHeil <1694964+geoHeil@users.noreply.github.com>
Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>
Co-authored-by: HPicatto <h.picatto@gmail.com>
Co-authored-by: Hernan Picatto <hernan.picatto@ascii.ac.at>

* chore: trigger build

* fix: cleanup delete not needed things

* chore: re-trigger

* chore: re-trigger

* fix: re-enable workflow dispatch

* fix: rename

* fix: CI

* fix: CI

* chore: update docs

* fix: deprecation

* fix: try fixing CI

* fix: try fixing CI

* fix: try fixing CI

* fix: try to fix CI

* fix: cleanup

* fix: refine dbt CI

* fix: CI

* fix: k

* fix: begin exploring dbr

* fix: lib

* fix: re-run from directory

* fix: cleanup

* update gitignore

* feat: prep PG for nominatim runtime after ingestion

* feat: upgrade owui

* fix: use direct run_id; still not submitting

* chore: prep for docling upgrade

* fix: library build version for EMR

* feat: upgrade docling

* chore: add more logs

* fix: emr bootstrap script

* chore: prep for ingestion albeit still running nominatim ingestion

* chore: reformat

* fix: hardcode

* fix: local S3 execution

* add ASCII_WANDB

* chore: make strict and actually fail in case of problems

* fix: tests, fix dbr hostname

* fix: docker

* fix docker more

* fix: dockerfile

* fix: local docker

* fix: version

* fix: docker paths

* fix: path

* fix: --frozen

* fix: cmd

* fix: cd

* fix: absolute entrypoint

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* k

* update functions

* fix: make local dockerfile work again

* fix: environment structure

* fix: emr_key_v2.pem

* k

* k

* fix: seed nodes generator script

* feat: separte remote lib

* test EMR in docker

* fix: prep for real thing

* fix: paths

* fix token

* fix: python version for dbt

* fix env

* fix: simplify launch

* k

* making it run on dbr

* fix: use large directory

* parse for PROD keys

* fix: disable OOM model

* fix: gov url

* fix: gov api url

* k

* feat: add graphql

* fix readonly

* fix: real pandas

* k

* k

* ingest_ddb_metadata_and_profile

* fix: gov ddb paths

* fix: stabilize profiling

* fix: ranking orbis

* chore: cleanup

* feat: refine add tie-breaker

* chore: further cleanup

* fix: dependencies a bit more; still not completed

* feat: make emr and dbr now finally fail on the same errors AttributeError: 'ExtractResult' object has no attribute 'top_domain_under_public_suffix' for edges step

* fix: execute on DBR e2e

* core: formatting

* feat: refine CI

---------

Co-authored-by: Maximilian Hess <maximilian.hess@ascii.ac.at>
Co-authored-by: Maximilian Heß <83235802+MaximilianHess@users.noreply.github.com>
Co-authored-by: Georg Heiler <georg.heiler@ascii.ac.at>
Co-authored-by: HPicatto <h.picatto@gmail.com>
Co-authored-by: Hernan Picatto <hernan.picatto@ascii.ac.at>